### ISSUE TITLE
Need help creating api in MVC 5

### ISSUE THREAD

**Issue by Ayman2G** [htset/Eshop-backend-.NETCore#1]

**Comment by htset** [comment]
Hello Ayman,
I am interested, you can send me the details
Haris

**Comment by Ayman2G** [comment]
do you receive this email ?

**Comment by htset** [comment]
What email? Apart from the one you sent me?

**Comment by Ayman2G** [comment]
Yes this exact one i just wanted to make sure i can contact you via email.
Here is a description of the work :

 so we have the mvc web app that users connect to (entity framework
authentication)  and fill in a form then the logic in the controller does
some calculations with these entries and has some methods that saves the
data model into database and generates certificates as excel worksheet
based on the entries in the form. i have created another interface in a
mobile app the goal is to send a certificat model from the mobile app to
the web app via the api and it should go through the controller logic flow
so that it can be saved and report generated as if someone used the web app
to enter the certificate model  entries then clicked the button save so the
data will be saved in the database and excel file generated i hope i was
clear i can provide more clarification if needed here is the web app link
https://drive.google.com/file/d/1AjxAfsEGaUK-9XBWHRgIO7CrWjN6xQNB/view?usp=sharing
I can also provide you with database and credentials if you want to run the
app to dee what it looks like

**Comment by htset** [comment]
Hello Ayman,
I have got the code and I am studying it. I will tell you tomorrow about
the cost
What is the deadline?

**Comment by htset** [comment]
Send me directly to haris.tsetsekas@gmail.com, instead of this thread

**Comment by Ayman2G** [comment]
I have a week as a deadline

**Comment by Ayman2G** [comment]
I can also send database and credentials for login if needed
